
version: 1.0.0.{build}
os: Visual Studio 2017
configuration: Release
platform: x64
clone_depth: 1
before_build:
- ps: >-
    $buildNumber = [Convert]::ToInt32($env:APPVEYOR_BUILD_NUMBER).ToString("0000")

    echo "Updating version in nuspec file"

    $root = $env:APPVEYOR_BUILD_FOLDER

    echo "Build folder is $root"

    $nuspecPathCS = "$root\Ndapi\Ndapi.csproj"

    [xml]$xmlCS = cat $nuspecPathCS

    if ($xmlCS.Project.PropertyGroup.Version.Contains("-")) {
      $xmlCS.Project.PropertyGroup.Version+="-$buildNumber"
    }

    echo "Version will be $($xmlCS.Project.PropertyGroup.Version)"

    $xmlCS.Save($nuspecPathCS)

    echo "Nuspec saved!"
    
    dotnet restore
build:
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    $root = $env:APPVEYOR_BUILD_FOLDER

    $nupkgPathCS = "$root\Ndapi\bin\Release\Ndapi.$($xmlCS.Project.PropertyGroup.Version).nupkg"

    echo "Nupkg path is $nupkgPathCS"

    echo "Pushing nuget artifact..."

    appveyor PushArtifact $nupkgPathCS

    echo "Nupkg pushed"
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ndapi/api/v2/package
  api_key:
    secure: FMzngpAnwhTtzr282EWaK7ku+a7u7IBwx/+gEIrQeKZwsTHJQ9g9DQ0DBzjfP9u+
