
version: 1.0.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 RC
clone_depth: 1
build_script:
- ps: >-
    $buildNumber = [Convert]::ToInt32($env:APPVEYOR_BUILD_NUMBER).ToString("0000")

    $env:DNX_BUILD_VERSION=$buildNumber

    dnvm upgrade

    dnu restore

    dnu pack --configuration=Release Ndapi\project.json

    $root = $env:APPVEYOR_BUILD_FOLDER

    $nupkgPathCS = "$root\Ndapi\bin\Release\Ndapi.1.0.0-alpha3-$buildNumber.nupkg"

    appveyor PushArtifact $nupkgPathCS
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ndapi/api/v2/package
  api_key:
    secure: FMzngpAnwhTtzr282EWaK7ku+a7u7IBwx/+gEIrQeKZwsTHJQ9g9DQ0DBzjfP9u+
