version: 1.0.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 CTP
configuration: Debug
platform: x86
clone_depth: 1
before_build:
- ps: >-
    $buildNumber = [Convert]::ToInt32($env:APPVEYOR_BUILD_NUMBER).ToString("0000")

    echo "Updating version in nuspec file"

    $root = $env:APPVEYOR_BUILD_FOLDER

    echo "Build folder is $root"

    $nuspecPathCS = "$root\Ndapi\Ndapi.nuspec"

    [xml]$xmlCS = cat $nuspecPathCS

    $xmlCS.package.metadata.version+="-$buildNumber"

    echo "Nuspec version will be $($xmlCS.package.metadata.version)"

    $xmlCS.Save($nuspecPathCS)

    echo "Nuspec saved!"
build:
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    $root = $env:APPVEYOR_BUILD_FOLDER

    echo "Packing nuget..."

    nuget pack "$root\Ndapi\Ndapi.csproj" -Properties "Configuration=Debug;Platform=x86" -OutputDirectory "$root\Ndapi\"

    $nupkgPathCS = "$root\Ndapi\Ndapi.$($xmlCS.package.metadata.version).nupkg"

    echo "Nupkg path is $nupkgPathCS"

    ls $nupkgPathCS

    echo "Nuget packed!"

    echo "Pushing nuget artifact..."

    appveyor PushArtifact $nupkgPathCS

    echo "Nupkg pushed"
test: off
artifacts:
- path: Ndapi\bin\$(configuration)\Ndapi.dll
  name: ndapi
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ndapi/api/v2/package
  api_key:
    secure: FMzngpAnwhTtzr282EWaK7ku+a7u7IBwx/+gEIrQeKZwsTHJQ9g9DQ0DBzjfP9u+
